import matplotlib.pyplot as plt

DEFAULT_WIDTH_PROP = 1000
DEFAULT_PLOT_COLOR = "1F78B4"
DEFAULT_PLOT_EDGE_COLOR = "EEEEEE"
DEFAULT_PLOT_COLOR_MAP_OPTIONS = "RdYlBu_r"


TRANSFORM_NONE = 0
TRANSFORM_LOG1P = 1
TRANSFORM_LOG = 2
TRANSFORM_MINUS_LOG = 3

TRANSFORM_OPTIONS = (
    (TRANSFORM_NONE, "none"),
    (TRANSFORM_LOG1P, "log1p"),
    (TRANSFORM_LOG, "log"),
    (TRANSFORM_MINUS_LOG, "-log"),
)

BED_DISPLAY_TILES = 1
BED_DISPLAY_WITH_INTORNS = 2
BED_DISPLAY_FLYBASE = 3
BED_DISPLAY_DOMAINS = 4
BED_DISPLAY_ARCS = 5
BED_DISPLAY_VERTICAL_LINES = 6

BED_DISPLAY_OPTIONS = (
    (BED_DISPLAY_TILES, "Tiles"),
    (BED_DISPLAY_WITH_INTORNS, "With introns"),
    (BED_DISPLAY_FLYBASE, "Flybase"),
    (BED_DISPLAY_DOMAINS, "Domains"),
    (BED_DISPLAY_ARCS, "Arcs"),
    (BED_DISPLAY_VERTICAL_LINES, "Vertical lines"),
)

BED_STYLE_STACKED = 1
BED_STYLE_COLLAPSED = 2
BED_STYLE_INTERLACED = 3

BED_STYLE_OPTIONS = (
    (BED_STYLE_STACKED, "Stacked"),
    (BED_STYLE_COLLAPSED, "Collapsed"),
    (BED_STYLE_INTERLACED, "Interlaced"),
)

AGGREGATE_FUNCTION_AVG = "mean"
AGGREGATE_FUNCTION_SUM = "sum"
AGGREGATE_FUNCTION_MIN = "min"
AGGREGATE_FUNCTION_MAX = "max"

AGGREGATE_FUNCTIONS_OPTIONS = (
    (AGGREGATE_FUNCTION_AVG, "mean"),
    (AGGREGATE_FUNCTION_SUM, "sum"),
    (AGGREGATE_FUNCTION_MIN, "min"),
    (AGGREGATE_FUNCTION_MAX, "max"),
)

HIC_DISPLAY_HIC = 0
HIC_DISPLAY_VIRTUAL4C = 1

HIC_DISPLAY_OPTIONS = (
    (HIC_DISPLAY_HIC, "HIC"),
    (HIC_DISPLAY_VIRTUAL4C, "Virtual 4C"),
)


BEDGRAPH_DISPLAY_NONE = 0
BEDGRAPH_DISPLAY_TRANSPARENT = 1
BEDGRAPH_DISPLAY_SOLID = 2
BEDGRAPH_DISPLAY_STACKED = 3

BEDGRAPH_DISPLAY_OPTIONS = (
    (BEDGRAPH_DISPLAY_TRANSPARENT, "Transparent"),
    (BEDGRAPH_DISPLAY_SOLID, "Solid"),
    (BEDGRAPH_DISPLAY_STACKED, "Stacked"),
)


BEDGRAPH_TYPE_HISTOGRAM = 0
BEDGRAPH_TYPE_LINECHART = 1

BEDGRAPH_TYPE_OPTIONS = ((BEDGRAPH_TYPE_HISTOGRAM, "Histogram"), (BEDGRAPH_TYPE_LINECHART, "Linechart"))

BEDGRAPH_STYLE_LINE = 0
BEDGRAPH_STYLE_LINE_WITH_BORDER = 1
BEDGRAPH_STYLE_AREA = 2
BEDGRAPH_STYLE_AREA_WITH_BORDER = 3

BEDGRAPH_STYLE_OPTIONS = (
    (BEDGRAPH_STYLE_LINE, "Line"),
    (BEDGRAPH_STYLE_LINE_WITH_BORDER, "Line with border"),
    (BEDGRAPH_STYLE_AREA, "Area"),
    (BEDGRAPH_STYLE_AREA_WITH_BORDER, "Area with border"),
)

COLOR_MAP_OPTIONS = [(color_map, color_map) for color_map in plt.colormaps()]
