# Generated by Django 2.0.3 on 2021-04-24 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tadeus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='chromsome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tadeus.Chromosome'),
        ),
        migrations.AddField(
            model_name='track',
            name='coordinate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='neighbourhood',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='track',
            name='neighbourhood_transform',
            field=models.CharField(choices=[('sum', 'sum'), ('avg', 'avg'), ('min', 'max')], default='sum', max_length=5),
        ),
        migrations.AlterField(
            model_name='trackfile',
            name='file_type',
            field=models.CharField(choices=[('BE', 'Bed'), ('BG', 'BedGraph'), ('BM', 'BedGraphMatrix'), ('HI', 'HiCMatrix'), ('4C', 'Virtual4C'), ('XA', 'XAxis')], max_length=2),
        ),
    ]
