# Generated by Django 2.0.3 on 2021-04-24 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tadeus', '0002_auto_20210424_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='chromsome',
            new_name='chromosome',
        ),
    ]
