# Generated by Django 2.0.3 on 2021-04-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tadeus', '0003_auto_20210424_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='hic_display_options',
            field=models.CharField(choices=[('hic', 'HIC'), ('v4c', 'Virtual 4C')], default='hic', max_length=3),
        ),
        migrations.AlterField(
            model_name='track',
            name='coordinate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='neighbourhood',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='track',
            name='neighbourhood_transform',
            field=models.CharField(choices=[('sum', 'sum'), ('avg', 'avg'), ('min', 'min'), ('max', 'max')], default='sum', max_length=5),
        ),
        migrations.AlterField(
            model_name='trackfile',
            name='file_type',
            field=models.CharField(choices=[('BE', 'Bed'), ('BG', 'BedGraph'), ('BM', 'BedGraphMatrix'), ('HI', 'HiCMatrix'), ('XA', 'XAxis')], max_length=2),
        ),
    ]
