DEFAULT_EDIT_ICON = 'fa-edit'
DEFAULT_BROWSER_ICON = 'fa-sliders-h'
DEFAULT_WIDTH_PROP = 1000

DEFAULT_PLOT_COLOR = '1F78B4'
DEFAULT_PLOT_EDGE_COLOR = 'EEEEEE'
DEFAULT_PLOT_COLOR_MAP_OPTIONS = 'RdYlBu_r'