# Generated by Django 3.1 on 2021-12-05 00:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('bedfileentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='datasources.bedfileentry')),
                ('ensembl_gene_id', models.CharField(blank=True, max_length=20, null=True)),
                ('gene_biotype', models.CharField(blank=True, max_length=20, null=True)),
                ('entrezgene_id', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('datasources.bedfileentry',),
        ),
        migrations.CreateModel(
            name='GeneToPhenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequent', models.BooleanField(default=False)),
                ('gene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontologies.gene')),
            ],
            options={
                'ordering': ['gene'],
            },
        ),
        migrations.CreateModel(
            name='Phenotype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db', models.CharField(max_length=10)),
                ('pheno_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('definition', models.CharField(max_length=1000, null=True)),
                ('comment', models.CharField(max_length=2000, null=True)),
                ('genes', models.ManyToManyField(related_name='phenotypes', through='ontologies.GeneToPhenotype', to='ontologies.Gene')),
                ('is_a', models.ManyToManyField(to='ontologies.Phenotype')),
            ],
        ),
        migrations.AddField(
            model_name='genetophenotype',
            name='phenotype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ontologies.phenotype'),
        ),
    ]
